---
title: "Eric_Hirsch_622_Assignment_1"
subtitle: "Predicting Sales Data" 
author: "Eric Hirsch"
date: "10/7/2022"
output:
  pdf_document:
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning =  FALSE, message = FALSE)
```

```{r, include=FALSE}
library(devtools)
library(roxygen2)
library(Hmisc)
library(psych)
library(tidyverse)
library(skimr)
library(purrr)
library(tidyr)
library(tidyverse)
library(gridExtra)
library(lubridate)
library(fastDummies)
library(data.table)
library(mltools)
library(MASS)
library(car)
library(patchwork)
library(ggthemes)
library(tinytex)
library(stats)
library(ggsci)
library(scales)
library(naniar)
library(caret)
library(pROC)
library(tidyverse)
library(Hmisc)
library(skimr)
#install.packages("devtools")
devtools::install_github("ericonsi/EHData", force=TRUE)
library(EHData)
library(patchwork)
library(gridExtra)
library(ggsci)
library(caret)
library(pROC)
library(car)
library(psych)
library(patchwork)
library(MASS)
library(lubridate)
library(e1071)
library(caTools)
library(class)
#library(mice)
```
```{r}

#dfTrain <- read.csv("C:\\Users\\erico\\Documents\\R\\Space\\train.csv")
#dfTest <- read.csv("C:\\Users\\erico\\Documents\\R\\Space\\test.csv")

dfTrain <- read.csv("D:\\Rstudio\\Cuny_622\\Space\\train.csv")
dfTest <- read.csv("D:\\Rstudio\\Cuny_622\\Space\\test.csv")

```


### 1. Data Exploration


#### A. Summary Statistics

```{r}


summary(dfTrain)
str(dfTrain)
```

```{r}


summary(dfTest)

```

```{r}

Group2 <- dfTrain %>% dplyr::select(PassengerId, Transported) %>% mutate(Transported=ifelse(Transported=='True',1,0))

Group2$Group <- sub("\\_.*", "", Group2$PassengerId)

Group2Sum <- Group2 %>%
  dplyr::group_by(Group) %>%
  dplyr::summarize(PredPercent= sum(Transported)/n(), count=n())

Group2SumGroups <- Group2Sum %>%
  filter(count>1)

hist(Group2SumGroups$PredPercent)


dfTrainA <- dfTrain

dfTrainA$Group <- Group2$Group

dfTrainAA <- inner_join(dfTrainA, Group2Sum, by="Group") %>% dplyr::select(-Group, -PredPercent)

dfTrainBB <- dfTrainAA %>%
  mutate(Transported = ifelse(Transported=="True",1,0))

boxplot(as.numeric(dfTrainBB$count), as.numeric(dfTrainBB$Transported))

Group2a <- dfTest %>% dplyr::select(PassengerId) 

Group2a$Group <- sub("\\_.*", "", Group2a$PassengerId)

Group2aSum <- Group2a %>%
  dplyr::group_by(Group) %>%
  dplyr::summarize(count=n())

dfTestA <- dfTest

dfTestA$Group <- Group2a$Group

dfTestAA <- inner_join(dfTestA, Group2aSum, by="Group") %>% dplyr::select(-Group)

```

```{r}
dfTrain1 <- na.omit(dfTrainAA)
dfTest1 <- EHPrepare_MissingValues_Imputation(dfTestAA, impute="median")
```


```{r}
library(stringr)
dfTrain1$Cabin1 <- substr(dfTrain1$Cabin,1,1)
dfTrain1$Cabin2 <- str_sub(dfTrain1$Cabin, - 1, - 1) 

dfTrain2 <- dfTrain1 %>%
  dplyr::select(-Cabin) %>%
  mutate(Transported=ifelse(Transported=="True",1,0))

dfTest1$Cabin1 <- substr(dfTest1$Cabin,1,1)
dfTest1$Cabin2 <- str_sub(dfTest1$Cabin, - 1, - 1) 

dfTest2 <- dfTest1 %>%
  dplyr::select(-Cabin)

dfTrain3 <- dfTrain2
dfTest3 <- dfTest2
```




```{r}


a <- EHSummarize_SingleColumn_Histograms(dfTrain3)
grid.arrange(grobs=a[c(1:6)], ncol=3)

EHExplore_OneContinuousAndOneCategoricalColumn_Boxplots(dfTrain3, "Transported")
#grid.arrange(grobs=b[c(1:8)], ncol=1)

EHSummarize_StandardPlots(dfTrain3, "Transported")

```

```{r}

dfNum <- dfTrain %>%
  dplyr::select(where(is.numeric)) 
dfNum <- na.omit(dfNum)

EHExplore_Multicollinearity(dfNum)
```


```{r}

dfTrain4 <- dfTrain3 %>%
  dplyr::select(-Name, -PassengerId)

PassengerID <- dfTest3$PassengerId
dfTest4 <- dfTest3 %>%
  dplyr::select(-Name, -PassengerId)

dfTrain5 <- EHPrepare_CreateDummies(dfTrain4, "Transported")
dfTest5 <- EHPrepare_CreateDummies(dfTest4, "Transported")

dfTest5 <- cbind(PassengerID, dfTest5)

dfTrain5Num <- dfTrain5 %>%
  dplyr::select(where(is.numeric)) 


```



```{r}


pca <- prcomp(dfNum, center = TRUE,scale. = TRUE)

summary(pca)


```

```{r}

#install_github("vqv/ggbiplot")
library(ggbiplot)
ggbiplot(pca, labels=dfx1$HomePlanet)

```

```{r}


library(factoextra)

fviz_nbclust(dfNum, kmeans, method = "wss")
k2 <- kmeans(dfNum, centers=6, iter.max = 10, nstart = 1)
fviz_cluster(k2, data = dfNum)
```

```{r}

dfNumC <- cbind(dfNum, Cluster = k2$cluster)

dfNumCSum <- dfNumC %>%
  group_by(Cluster) %>%
  dplyr::summarise(across(everything(), mean))

dfNumCSumS <- scale(dfNumCSum)
qq <- as.matrix(dfNumCSumS)

heatmap(qq, Rowv = NA, Colv = NA)

#EHExplore_OneContinuousAndOneCategoricalColumn_Boxplots(dfNumC, "Cluster")
```


```{r}
dfSmall <- dfTrain5 %>%
  dplyr::filter(row_number() %% 10 ==1) 

qq <- EHModel_RandomForest(dfTrain5, "Transported")
```

```{r}

 #BEST MODEL!!
library(gbm)
boost=gbm(Transported ~ . ,data = dfTrain5, distribution = "gaussian",n.trees = 10000,
                  shrinkage = 0.01, interaction.depth = 4)
boost

summary(boost) #Summary gives a table of Variable Importance and a plot of Variable Importance

predictions2 <- as.data.frame(predict(boost, dfTest5)) %>%
  rename(Transported = 1) 

result <- as.data.frame(cbind(dfTest5$PassengerID, predictions2$Transported)) %>%
  rename(PassengerID = 1, Transported=2) %>%
  mutate(Transported = ifelse(Transported>.5,'True','False'))



write_csv(result, "C:\\Users\\Eric\\Desktop\\SVMpredictions5.csv")

```


```{r}

ww <- EHModel_Regression_Logistic(dfTrain5, 'Transported',returnLM = TRUE)
ww4 <- glm(Transported ~., data = dfTrain5, family = binomial(link = "logit"))


predictions2 <- as.data.frame(predict(ww4, dfTest5)) %>%
  rename(Transported = 1) 

result <- as.data.frame(cbind(dfTest5$PassengerID, predictions2$Transported)) %>%
  rename(PassengerID = 1, Transported=2)   %>%
  mutate(Transported = ifelse(Transported>.5,'True','False'))

write_csv(result, "C:\\Users\\Eric\\Desktop\\SVMpredictions5.csv")

```



```{r}

predictions2 <- as.data.frame(predict(qq$rf, dfTest5)) %>%
  rename(Transported = 1) 


#dfTest2$Group <- sub("\\_.*", "", dfTest2$PassengerId)

result <- as.data.frame(cbind(dfTest5$PassengerID, predictions2$Transported)) %>%
  rename(PassengerID = 1, Transported=2) 

dfGroups <- result
dfGroups$Group <- sub("\\_.*", "", result$PassengerID)
result$Group <- sub("\\_.*", "", result$PassengerID)
dfGroups$Transported = as.numeric(dfGroups$Transported)
dfGroups$Transported = ifelse(dfGroups$Transported==1,0,1)

dfGroupsSum <- dfGroups %>%
  group_by(Group) %>%
  summarize(PredPercent= sum(Transported)/n())

dfGroupsSum$Determination <- ifelse(dfGroupsSum$PredPercent>.5, "True", ifelse(dfGroupsSum$PredPercent==.5, "None", "False"))

new <- as.data.frame(lapply(result, function(x) dfGroupsSum$Determination[match(x, dfGroupsSum$Group)]))

result2 <- cbind(result, "Determination"=new$Group)

result3 <- result2 %>%
  mutate(Transported = ifelse(Transported==1,"False","True")) %>%
  mutate(Transported2 = ifelse(Determination=="None",Transported,Determination))  %>%
  dplyr::select(PassengerID, Transported2) %>%
  dplyr::rename(Transported=2)




#  mutate(Transported = ifelse(Transported==1,'False','True'))



write_csv(result3, "C:\\Users\\Eric\\Desktop\\SVMpredictions4.csv")

```

```{r}

#b <- EHModel_SVM(dfx2RFSmall, "Transported", method="radial")
c <- EHModel_Regression_Logistic(dfTrain5, "Transported", returnLM = TRUE)

```

```{r}
svm2 <- train(Transported~., data=dfTrain5, method="svmLinear", preProcess = c("center","scale"))
```

```{r}

predictions2 <- as.data.frame(predict(svm2, dfTest5)) %>%
  rename(Transported = 1) %>%
  mutate(Transported =ifelse(Transported>.5,1,0))


result <- as.data.frame(cbind(dfTest5$PassengerID, predictions2$Transported)) %>%
  rename(PassengerID = 1, Transported=2) %>%
  mutate(Transported = ifelse(Transported==1,'True','False'))



write_csv(result, "C:\\Users\\Eric\\Desktop\\SVMpredictions2.csv")



```



```{r}

rf1 <-train(Transported~., data=dfTrain5, method="rf")
 

model = rf1
predictions <- predict(model,newdata=dfTest5)
predictions <- data.frame(as.vector(predictions))
predictions$PassengerId <- dfTest5$PassengerID
predictions[,c(1,2)] <- predictions[,c(2,1)]
colnames(predictions) <- c("PassengerID", "Transported")
write_csv(predictions, "C:\\Users\\erico\\Desktop\\SVMpredictions2.csv")

makePredictions2 <- function(model)
{
predictions <- predict(model,newdata=dfTest5)
predictions <- data.frame(as.vector(predictions))
predictions$PassengerId <- dfTest5$PassengerID
predictions[,c(1,2)] <- predictions[,c(2,1)]
colnames(predictions) <- c("PassengerID", "Transported")
write_csv(predictions, "C:\\Users\\erico\\Desktop\\SVMpredictions2.csv")
#write_csv(predictions, "D:\\RStudio\\CUNY_621\\Final\\predictionsABC.csv")
}

#makePredictions2(a$rf)
#makePredictions2(b$svm)
#makePredictions2(c)

```
```{r}

#x <- predict(a$rf, dfTest5)
x <- as.data.frame(x)

```

```{r}
dfx3Small <- dfx3 %>%
  filter(row_number() %% 5 ==1)

EHModel_SVM(dfx3Small, "Transported", method="poly")
```

```{r}
library(factoextra)

fviz_nbclust(dfNum, kmeans, method = "wss")

k2 <- kmeans(dfNum, centers=3, iter.max = 10, nstart = 1)
fviz_cluster(k2, data = dfNum)
```


```{r}
library(xgboost)
library(caret)
#BEST MODEL 221106-1123

#make this example reproducible
set.seed(0)

dfTrain5q <-dfTrain5
dfTest5q <- dfTest5

dfTrain5q$Transported = as.character(dfTrain5q$Transported)
dfTrain5$Transported = as.character(dfTrain5$Transported)

dfTrain5q$Group = ifelse(dfTrain5q$count>1,1,0)
dfTrain5$Group = ifelse(dfTrain5$count>1,1,0)

dfTrain5q$Inter_CountShop = dfTrain5q$count*dfTrain5q$ShoppingMall

train_x <- dfTrain5q %>%
  dplyr::select(-Transported, -count)
train_y <- dfTrain5q %>%
  dplyr::select(Transported)

dfTest6 <- dfTest5q
dfTest6$Transported = "1"

dfTest6$Group = ifelse(dfTest6$count>1,1,0)
dfTest6$Inter_CountShop = dfTest6$count*dfTest6$ShoppingMall

test_x <- dfTest6 %>%
  dplyr::select(-Transported,-PassengerID, -count)
test_y <- dfTest6 %>%
  dplyr::select(Transported)

#define final training and testing sets
xgb_train <- xgb.DMatrix(data = as.matrix(train_x), label = as.matrix(train_y))
xgb_test <- xgb.DMatrix(data = as.matrix(test_x), label = as.matrix(test_y))

#tRIAL AND ERROR GAVE 55 AS BEST with max.depth at 3 - COULD TRY OTHERS

model2 <- xgb.train(data = xgb_train, max.depth = 100, nrounds = 10055)

```

```{r}


predictions <- predict(model2,newdata=xgb_test)
predictions <- data.frame(as.vector(predictions)) 
predictions$PassengerId <- dfTest5$PassengerID
predictions[,c(1,2)] <- predictions[,c(2,1)]
colnames(predictions) <- c("PassengerID", "Transported")

predictions <- predictions %>%
  mutate(Transported=ifelse(Transported>.5,'True','False'))

#write_csv(predictions, "C:\\Users\\Eric\\Desktop\\XGBpredictions1.csv")
write_csv(predictions, "C:\\Users\\erico\\Desktop\\XGBpredictions1.csv")

makePredictions2 <- function(model)
{
predictions <- predict(model,newdata=dfTest5)
predictions <- data.frame(as.vector(predictions))
predictions$PassengerId <- dfTest5$PassengerID
predictions[,c(1,2)] <- predictions[,c(2,1)]
colnames(predictions) <- c("PassengerID", "Transported")
write_csv(predictions, "C:\\Users\\erico\\Desktop\\SVMpredictions2.csv")
#write_csv(predictions, "D:\\RStudio\\CUNY_621\\Final\\predictionsABC.csv")
}

#makePredictions2(a$rf)
#makePredictions2(b$svm)
#makePredictions2(c)

```




